testing_mode = true
payment_provider = "stripe" #bmac if using Buy Me A Coffee
stripe_api_key = "rk_test_51NfAVpFFI1XJR0YFXwhiqvWKtnadUu1WixW57LP4IWUQ5byUOWetqDSA0djJ7LTssbiUhkB7w8tFjwtSzaqnVMqO00DG11tNMK" #only needed if using Stripe
stripe_api_key_test = "sk_test_51NfAVpFFI1XJR0YFxq1Ew4vu9L53rX4sNy8AE5AkX0yLjbJ2yI4HO45UVxgZXWixGWipq2TJQkifD2dNDSPg1zFg00n1k3YcSi" #only needed if using Stripe
stripe_link = "https://buy.stripe.com/test_7sI17Q89Z3CLgOk8ww" #only needed if using Stripe
stripe_link_test = "https://buy.stripe.com/test_7sI17Q89Z3CLgOk8ww" #only needed if using Stripe
client_id = "364206349579-4kajukpiui6khnrqg4e2g23jnk0imons.apps.googleusercontent.com"
client_secret = "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"
redirect_url_test = 'http://localhost:8501/'
redirect_url = "https://flower.streamlit.app/"
bmac_api_key = "ey..." #only needed if using buy me a coffee
bmac_link = "https://www.buymeacoffee.com/..." #only needed if using buy me a coffee